server:  port: 8080  servlet:    context-path: /log:  trace-id:    enabled: true    app-name: ${spring.application.name}    header: X-TRACE-ID  desensitization:    replace-fields: userName,mobile    erase-fields: age,password    drop-fields: sexspring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://root:123456@192.168.137.105:3306/zakiis?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true    username: root    password: 123456  application:    name: springboot-test

mybatis:
  cipher:
    enabled: true
    secret: 14fc710f878246a74ca7ca246173339b
    iv: ba7ca246175339b14fc720f873246a7d  mapper-locations:  - classpath*:mapper/*.xml  print-sql: true